name: Hercules Analysis

on: [push]

jobs:
  hercules-charts:
    runs-on: ubuntu-latest
    name: Generate Burndown Charts
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      
      - name: Run Hercules Analysis
        run: |
          docker run --rm -v $(pwd):/repo --workdir=/repo \
            srcd/hercules:latest \
            /bin/bash -c \
            'hercules --burndown --burndown-people --pb . | labours -m burndown-person -f pb --disable-projector -o hercules_charts \
            && cd hercules_charts \
            && tar -cf ../hercules_charts.tar * \
            && cd .. \
            && rm -r hercules_charts'
      
      - uses: actions/upload-artifact@master
        with:
          name: hercules_charts
          path: hercules_charts.tar
